# Generated by Django 5.0.6 on 2024-06-05 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_duration', models.DurationField()),
                ('organizer_name', models.CharField(max_length=100)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('organizer_phone', models.CharField(max_length=15)),
                ('event_url', models.URLField()),
                ('categories', models.ManyToManyField(to='events.eventcategory')),
            ],
        ),
        migrations.CreateModel(
            name='VenueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_duration', models.DurationField()),
                ('organizer_name', models.CharField(max_length=100)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('organizer_phone', models.CharField(max_length=15)),
                ('event_location', models.CharField(max_length=200)),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.TextField()),
                ('categories', models.ManyToManyField(to='events.eventcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Venue', 'Venue'), ('Online', 'Online')], max_length=10)),
                ('event_id', models.PositiveIntegerField()),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event_type', 'event_id')},
            },
        ),
    ]
