# Generated by Django 5.0.6 on 2024-06-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_onlineevent_event_image_venueevent_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueevent',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
