# Generated by Django 5.0.6 on 2024-06-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_venueevent_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineevent',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
