# Generated by Django 5.0.6 on 2024-06-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_onlineevent_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
